plugins {
    id 'java-platform'
}

group = 'cloud.wondrify'

javaPlatform {
    allowDependencies()
}

dependencies {
    constraints {
        for (Project subproject : rootProject.subprojects) {
            if (subproject.path == project.path || !(subproject.name in rootProject.ext.publishedProjects)) {
                continue // ignore self
            }

            api project(":${subproject.path}")
        }

        // Core is built by the included build in asset-pipeline/. The Gradle plugin is too, but gradle dependencies are
        // separate from build dependencies so it is not included in the bom
        api "cloud.wondrify:asset-pipeline-core:$version"
    }
}

apply {
    plugin 'cloud.wondrify.publish-config'
}