=== Configuration

Asset-Pipeline has several configuration options for use with grails 3. For most cases the configuration options listed in the Gradle guide pertain to grails3. Some subtle differences is the concept of development runtime vs. build time. If you want settings to apply to both development runtime and build time the properties have to be duplicated in your applications `application.yml` project. This is currently a limitation in how grails reads configuration files and gradle conveys properties.

Most build time options like `skipNonDigests` or `enableGzip` will never need specified in this YAML file as they will never be used during development runtime. It is also possible to disable development runtime entirely. In this scenario assets will always be packaged with the application and not monitored for changes unless gradle continuous build is utilized. Simply set `assets { developmentRuntime = false}` in your `build.gradle` file.

Example yaml:

[source,yml]
----
grails:
  assets:
    bundle: true #dont individually require files in development
    storagePath: /path/to/store #automatically copy assets to external folder on startup
----

==== Lookup Cache

In a compiled application the asset filter caches what it finds for each url it is asked for, so it does not look the same url up again. The cache holds at most `maxCacheSize` assets, 10000 unless configured, and keeps those asked for most often. It holds as many urls that matched no asset apart from them, so requests for urls that don't exist never push out an asset the application serves.

[source,yml]
----
grails:
  assets:
    maxCacheSize: 10000
----

An application that serves more distinct assets than that can raise it; an evicted url is only looked up again. `0` turns the cache off. Development, where assets are compiled as they are asked for, does not use it.

The setting can also be given as a system property, `-Dgrails.assets.maxCacheSize=50000`. Grails does not map an environment variable such as `GRAILS_ASSETS_MAXCACHESIZE` onto `grails.assets`, so to take it from one, use a placeholder: `maxCacheSize: ${ASSET_CACHE_SIZE:10000}`.

==== Mappings and Asset Taglib URLs

In many cases you may want to change the URL for which to include your static assets. This can be useful when using a CDN or perhaps even using nginx to serve your static assets.

To change the URL for your taglibs use the following configuration option:

[source,yml]
----
grails:
  assets:
    url: http://cdn.example.com/
----

Now your files are going to reference the CDN when running in the production environment. To go with this feature, you can have your application automatically copy your asset files out of your base WAR file on startup of your application. Optionally the asset URL config can also be defined as a closure that takes a request argument.

[source,groovy]
----
grails.assets.url = { request ->
	if(request.isSecure()) {
		return "https://cdn.example.com/"
	} else {
		return "http://cdn.example.com/"
	}
}
----

This allows more fine grained control of your asset URLs based on the incoming request. An example, might be SSL detection or even changing CDN region by source IP.

NOTE: To use an asset closure config must be placed in an `application.groovy` file instead of `application.yml`

[source,yml]
----
grails:
  assets:
    storagePath: /var/cdn/path
----

You can also change the default Tomcat path for both debugging and file inclusion using the `mapping` config option.

[source,yml]
----
grails:
  assets:
    mapping: assets
----

For all these configuration options, you will want to put these config values in the appropriate environment in `application.yml` or in groovy format in `application.groovy`.

